name: Docker Image CI

on:
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '* 1 * * *'
  push:

env:
  DOCKER_REPO: mahoney-playground/docker-cache-action
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache docker
      uses: actions/cache@v1
      env:
        cache-name: docker-cache-1
      with:
        path: /tmp/docker_cache
        key: ${{ env.cache-name }}-${{ github.run_number }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Restore docker
      run: ./.github/restore.sh ${{ github.event_name }}
      shell: bash

    - name: Build App with Docker
      run: docker build . -t docker-cache-action-app:${GITHUB_SHA}
      shell: bash

    - name: Backup docker
      run: ./.github/backup.sh
      shell: bash
